name: rnaseq-nf
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: rnseq-nf ci
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11.0.4']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: Cache Nextflow environment
        uses: actions/cache@v2
        with:
          path: |
            work
            .nextflow/
          key: ${{ runner.os }}-nextflow-${{ hashFiles('**/nextflow.config') }}
          restore-keys: |
            ${{ runner.os }}-nextflow

      - name: Tests
        run: |
          pwd
          ls -la
          export CAPSULE_LOG=none
          curl -fsSL get.nextflow.io | bash
          ./nextflow run . -profile docker -resume
        env:
          NXF_ANSI_LOG: false

      - name: Post-Tests
        run: |
          pwd
          ls -la
          ls -la work
          du -sh work
          echo ${{ runner.os }}-nextflow-${{ hashFiles('work/**') }}
          echo ${{ runner.os }}-nextflow-${{ hashFiles('.nextflow/cache/**') }}
          echo ${{ runner.os }}-nextflow-${{ hashFiles('**/nextflow.config') }}
          egrep -e '(Cached|Submitted) process ' .nextflow.log | cut -d- -f3-

